### PR TITLE
Add command skipto to bot.py (#1486)

### PR DESCRIPTION
**Pull request by dannytb**
skipto command removes the songs at the front of the playlist until the
desired song is reached

After creating your pull request, tick these boxes if they are applicable to you.

- [X] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [X] I have tested my changes on Python 3.5/3.6

----

### Description
This is a feature request from #1486. The skipto command shares similar functionality with the skip command. The command takes an integer as an index and removes every song before that index in the queue, including the currently playing song. The permission to use the skipto command is not given to the default permission group, because the command does not require a vote to run. Japanese translations were added for the new discord messages, but they were taken from google translate so they could be wrong.

### Related issues (if applicable)
#1486

### CODE REVIEW

**Review by maquikun — APPROVED** [review]
Was working, but now its just skipping to random songs.

**Review by AutumnClove — APPROVED** [review]
Looks good to me, needs black ran over it

**Comment by AutumnClove** [comment]
@dannytb can you run black over your files so I can merge?

**Comment by AutumnClove** [comment]
Unable to get working, continues to skip songs once used, I don't wanna attempt to fix and mess anything up can you look into this?

**Comment by BabyBoySnow** [comment]
Closed no response from OP. If OP fixes I'll reopen.

**Pull request closed without merging**
