### PR TITLE
Optimize play commands

### PR DESCRIPTION
**Pull request by itsTheFae**
- [x] I have tested my changes against the `dev` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.8.10 or higher
- [x] I have ensured my code is formatted using [Black](https://github.com/psf/black)

----

### Description

This PR includes a complete overhaul of ytdl information extraction and updates bits that directly interact with extracted info.  The primary focus of this PR is to increase speed of the bot when processing playlists, but several changes are included.  

A full list of noteworthy changes:
  - Updates `shuffleplay` to shuffle playlist entries before they are queued.
  - Adds playlist name and other details to `pldump` generated files.
  - Enable `pldump` command to send file to invoking channel if DM fails.
  - Updates Now Playing Status to use custom status and activity *(experimental)*.
  - Adds stream support to autoplaylist entries, if they are detected as a stream.
  - Adds stream support to regular play command, if input is detected as a stream.
  - Adds playlist link support to autoplaylist entries. *(experimental)*
  - Asks if user wants to queue the playlist when using links with playlist and video IDs in them.
  - Include thumbnail in now-playing for any tracks that have it.
  - Remove all extraneous calls to extract_info, and carry extracted info with their player entries.
  - Adds `YtdlResponseDict` to act as a typed interface to the variable data of ytdl extractors.
  - Expansion of Spotify API to enable faster enqueue of Spotify playlists and albums.  

This update does not include complete i18n or entirely consistent UI (embed vs message) content.  
That aside, It should be ready for extensive testing. 

### Related issues (if applicable)

Potentially closes:  #2376  #2375  #1587 and #1462

### CODE REVIEW

**Review by DestinyofYeet — APPROVED** [review]
Looks good, lets test

**Comment by BabyBoySnow** [comment]
EXTENSIVE TESTING PENDING.

**Comment by BabyBoySnow** [comment]
Using directly from branch, seems to be working well 👍

**Comment by DestinyofYeet** [comment]
Fine to merge IMO if it works.

**Comment by itsTheFae** [comment]
I have not seen any total show stoppers while using it myself.   If folks are OK with it in this state I'm OK with this being merged whenever.

**Pull request merged**
