### PR TITLE
Add uptime command

### PR DESCRIPTION
**Pull request by itsTheFae**
- [x] I have tested my changes against the `dev` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.10 or higher
- [x] I have ensured my code is formatted using [Black](https://github.com/psf/black)

----

### Description

Adds user-requested `uptime` command for displaying bot uptime remotely.  As the bot measures its uptime by storing a starting time stamp, the time given by `uptime` may not match the time shown by a system-level service / process manager.

### CODE REVIEW

**Comment by BabyBoySnow** [comment]
which issue # if you have it

**Comment by itsTheFae** [comment]
This was requested in the discord by user currently named `Uira`

**Comment by itsTheFae** [comment]
I think this got broken when you resolved it.

**Comment by BabyBoySnow** [comment]
that's what I get for using the resolver on the webpage should've done it from vsc lol

**Pull request merged**
