### PR TITLE
New search output

### PR DESCRIPTION
**Pull request by vonDassendorf**
After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5.3 or higher

----

### Description
This adds an option to display the search results as a list instead of the reaction system.
It also adds an option to change the default amount of search results returned.

### Related issues (if applicable)
#1929

### CODE REVIEW

**Comment by vonDassendorf** [comment]
If I get it right this repo is not going to be updated anymore so should i close this PR??

**Comment by AutumnClove** [comment]
> If I get it right this repo is not going to be updated anymore so should i close this PR??

@vonDassendorf Hello, no there's no need to close the PR, we're in the process of getting progress started with the repo again, I do apologize for the delay. We appreciate your patience.

**Comment by vonDassendorf** [comment]
> 
> 
> > If I get it right this repo is not going to be updated anymore so should i close this PR??
> 
> @vonDassendorf Hello, no there's no need to close the PR, we're in the process of getting progress started with the repo again, I do apologize for the delay. We appreciate your patience.

Ahh great! No hurry really, you're doing a great job!

**Comment by AutumnClove** [comment]
@vonDassendorf would you be able to merge the review branch into this and get it up to date so it's ready  for a merge, I'm hoping to have one soon.

**Comment by vonDassendorf** [comment]
Sure, I'll try to have it reade asap

**Comment by vonDassendorf** [comment]
@AutumnClove review branch is merged  and everything seems to work as expected.

**Review by AutumnClove — APPROVED** [review]
Nice

**Pull request merged**
