### PR TITLE
Config: Implemented DeleteNowPlaying option and fixed the DeleteMessages description.

### PR DESCRIPTION
**Pull request by RheaAyase**

### CODE REVIEW

**Comment by jayktaylor** [comment]
As it has been 2 months without activity on this PR, it will be closed. If you wish to PR this feature again, please merge your changes and PR to the `review` branch.

**Comment by RheaAyase** [comment]
Hello,

I'm afraid that this is not how open source contribution works. I commited my changes, now it's your business. Take it or leave it. Cheers!

Radka :]

**Comment by jayktaylor** [comment]
We don't accept pull requests that are pointed at the wrong branch. Thank you for your contribution, though.

**Comment by RheaAyase** [comment]
I communicated it on Discord, nobody told me about different branch, and it was okay'd there after I submitted the pull request. I don't think that there was even that branch back then.

Further on the topic: #666

**Pull request closed without merging**
