### PR TITLE
Update the Using section of the wiki

### PR DESCRIPTION
**Pull request by AleanaA**
After creating your pull request, tick these boxes if they are applicable to you.

- [ ] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [ ] I have tested my changes on Python 3.5.3 or higher

----

### Description
Added `!resetplaylist` to the Admin section of commands.md

Added `LegacySkip`, `LeaveServerWithoutOwner`, and `UseAlias` to configuration.md
Added `CustomEmbedFooter` with a `Review Only` badge to configuration.md

Added 3 common problems seen in the help server to troubleshooting.md:
`ValueError: Invalid format '.' for '%' style` - py 3.8 breaks the master branch
`TypeError: __new__() got an unexpected keyword argument 'deny_new'` - old versions of d.py break the bot

Resolved linting being angry about stupid things in commands.md, configuration.md, and troubleshooting.md

### CODE REVIEW

**Comment by srhinos** [comment]
@AleanaA is this something that we should try and get merged in?

**Comment by AleanaA** [comment]
@srhinos Given those sections are heavily out of date and missing information that's newer than 2 years ago, it's not a bad idea to get that whole section updated. I wanted to update to wiki here first before trying to move to RTD or any alternative like was discussed.

**Comment by srhinos** [comment]
> 
> 
> @srhinos Given those sections are heavily out of date and missing information that's newer than 2 years ago, it's not a bad idea to get that whole section updated. I wanted to update to wiki here first before trying to move to RTD or any alternative like was discussed.

for sure I agree,

**Review by srhinos — APPROVED** [review]

**Comment by srhinos** [comment]
Feel free to merge!

**Pull request merged**
