### PR TITLE
A maybe working restart command

### PR DESCRIPTION
**Pull request by AutumnClove**
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the pull request.

- [x ] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x ] I have tested my changes on Python 3.5/3.6

----

### CODE REVIEW

**Comment by ghost** [comment]
Maybe you could implement a check if it's Windows, Mac or Linux, because .bat files are Windows-only.

**Review by MattBSG — CHANGES_REQUESTED** [review]
Support for other OSes

**Review by jayktaylor — CHANGES_REQUESTED** [review]
This isn't going to work. Raising an exception will terminate the function, thus a subprocess will never start. A subprocess is not really going to be suitable, because CREATE_NEW_CONSOLE will just open a new command window. And, as pointed out by others, this will only "work" on Windows.

**Comment by AutumnClove** [comment]
haaalp I can't get it to go back to tab size 4 ;-;

**Comment by MattBSG** [comment]
Author moved issue to #1494

**Pull request closed without merging**
