### PR TITLE
Added a command that adds the currently playing song to the autoplaylist

### PR DESCRIPTION
**Pull request by ConnorPickles**
adds the currently playing song to the autoplaylist. checks to make sure duplicates are not added

### CODE REVIEW

**Comment by Zenrac** [comment]
An other way:
```
    async def cmd_pladd(self, player, song_url=None):
        """
        Usage:
            {command_prefix}pladd current song
            {command_prefix}pladd song_url

        Adds a song to the autoplaylist.
        """

        #No url provided
        if not song_url:
            #Check if there is something playing and get the information
            if player._current_entry:
                song_url = player._current_entry.url
                title = player._current_entry.title

            else:
                raise exceptions.CommandError('There is nothing playing.', expire_in=20)

        else:
            #Get song info from url
            info = await self.downloader.safe_extract_info(player.playlist.loop, song_url, download=False, process=False)
            title = info.get('title', '')

            #Verify proper url
            if not title:
                raise exceptions.CommandError('Invalid url. Please insure link is a valid YouTube, SoundCloud or BandCamp url.', expire_in=20)
                
        #Verify song isn't already in our playlist
        for url in self.autoplaylist:
            if song_url == url:
                return Response("Song already present in autoplaylist.", delete_after=30)

        self.autoplaylist.append(song_url)
        write_file(self.config.auto_playlist_file, self.autoplaylist)
        self.autoplaylist = load_file(self.config.auto_playlist_file)
        return Response("Added %s to autoplaylist." % title, delete_after=30)
```

**This requires that you add a new function in utils.py**
```
def illegal_char(string, chars):
    illegal = re.compile(chars)
    if illegal.search(string):
        return True
    else:
        return False
```

**And include it in bot.py**
`from musicbot.utils import load_file, write_file, sane_round_int, illegal_char`

**The reverse command: (remove)**
```
    async def cmd_plremove(self, player, song_url=None):
        """
        Usage:
            {command_prefix}plremove current song
            {command_prefix}plremove song_url

        Remove a song from the autoplaylist.
        """

        #No url provided
        if not song_url:
            #Check if there is something playing
            if not player._current_entry:
                raise exceptions.CommandError('There is nothing playing.', expire_in=20)

            #Get the url of the current entry
            else:
                song_url = player._current_entry.url
                title = player._current_entry.title

        else:
            #Get song info from url
            info = await self.downloader.safe_extract_info(player.playlist.loop, song_url, download=False, process=False)

            #Verify proper url
            if not info:
                raise exceptions.CommandError('Invalid url. Please insure link is a valid YouTube, SoundCloud or BandCamp url.', expire_in=20)

            else:
                title = info.get('title', '')

#Verify that the song is in our playlist
        for url in self.autoplaylist:
            if song_url == url:
                self.autoplaylist.remove(song_url)
                write_file(self.config.auto_playlist_file, self.autoplaylist)
                self.autoplaylist = load_file(self.config.auto_playlist_file)
                return Response("Removed %s from the autoplaylist." % title, delete_after=30)

        return Response("Song not present in autoplaylist.", delete_after=30) 
```

Thanks to Selkea from #921

**Comment by Soitora** [comment]
+1

**Comment by Doam** [comment]
```
Traceback (most recent call last):
  File "C:\Users\*\MusicBot\musicbot\bot.py", line 1881, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\*\MusicBot\musicbot\bot.py", line 1279, in cmd_playadd
    write_file(self.autoplaylist_file, self.autoplaylist)
  File "C:\Users\*\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 264, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'autoplaylist_file'
```
What's the problem? Added all the instructions.

**Comment by Adeft** [comment]
Hey i love this! Is it also possible to !removepl if the link is in the autoplaylist it will delete/remove it.?

**Comment by Zenrac** [comment]
@Doam Sorry, my mistake, I have uptaded the commands plremove and pladd. 
@Adeft It will delete the link in the autoplaylist.

**Comment by Adeft** [comment]
@zenrac update the whole MusicBot folder. Could not get the commands to work?

**Comment by Adeft** [comment]
@zenrac @ConnorPickles is it possible to make it so its skips instead of delete the songs in autoplaylist if the link cant be played?
"If the bot is unable to retrieve info about a song in the autoplaylist it deletes it."

**Comment by jaschuu** [comment]
@zenrac with cmd_plremove i would like it to also skip the current playing song as well as remove it from the autoplaylist how would i go about adding this to you command?

**Comment by Zenrac** [comment]
@Adeft delete this line and add a "pass" instead

@jaschuu At the end, add the following line : 
await self.on_player_finished_playing(player)

**Comment by jaschuu** [comment]
@zenrac 
like this? thats not working for me, sorry i am very new to this coding

skip

**Comment by Zenrac** [comment]
Yes because the command ends when a "**return**" is used.

You have to replace **return Response("message")** for **await self.safe_send_message(channel, "message")**

I have not tested the following command
```
    async def cmd_plremove(self, player, channel, song_url=None):
        """
        Usage:
            {command_prefix}plremove current song
            {command_prefix}plremove song_url

        Remove a song from the autoplaylist.
        """

        #No url provided
        if not song_url:
            #Check if there is something playing
            if not player._current_entry:
                raise exceptions.CommandError('There is nothing playing.', expire_in=20)

            #Get the url of the current entry
            else:
                song_url = player._current_entry.url
                title = player._current_entry.title

        else:
            #Get song info from url
            info = await self.downloader.safe_extract_info(player.playlist.loop, song_url, download=False, process=False)

            #Verify proper url
            if not info:
                raise exceptions.CommandError('Invalid url. Please insure link is a valid YouTube, SoundCloud or BandCamp url.', expire_in=20)

            else:
                title = info.get('title', '')

#Verify that the song is in our playlist
        for url in self.autoplaylist:
            if song_url == url:
                self.autoplaylist.remove(song_url)
                write_file(self.config.auto_playlist_file, self.autoplaylist)
                self.autoplaylist = load_file(self.config.auto_playlist_file)
                await self.safe_send_message(channel, "Removed %s from the autoplaylist." % title)
                if song_url == player._current_entry.url:
                    await self.on_player_finished_playing(player)
                return
        return Response("Song not present in autoplaylist.", delete_after=30) 
```

Btw, i've added a small condition, if the url removed is not the song that is currently playing, it will not be skipped. (seems logic)

**Comment by TicWE** [comment]
Hey guys, I'm not experienced at all in programming so I don't really know how all this works. Could someone explain me how to add this to my bot please ?

**Comment by Zenrac** [comment]
In bot.py,
If you have any more question, please read this 
https://github.com/Just-Some-Bots/MusicBot/wiki/Modification

**Comment by TicWE** [comment]
Just pasted the command between to other commands, restarted my bot but the bot doesn't recognise the command when I'm typing "!help addnp"

**Comment by TicWE** [comment]
Is it possible to add every songs from a playlist with this, or multiple songs at once ?

**Comment by Zenrac** [comment]
It took me a lot of times but it's the pladd that can add all the songs from a playlist
```
    async def cmd_pladd(self, player, channel, author, song_url=None):
        """
        
            =pladd
            =pladd url

Add a song to the current autoplaylist
        """
        self.autoplaylist = load_file(self.autoplaylist_file)
        is_playlist = False
        info = ""
        #No url provided       
        if not song_url:
            #Check if there is something playing and get the information
            if player._current_entry:
                song_url = player._current_entry.url
                title = player._current_entry.title

            else:
                raise exceptions.CommandError("No song currently, specify an URL.", expire_in=20)

        else:
            #Get song info from url
            try:
                info = await self.downloader.extract_info(player.playlist.loop, song_url, download=False, process=False)
                title = info.get('title', '')
            except:
                raise exceptions.CommandError('Invalid URL, use a Youtube, SoundCloud or BandCamp link.', expire_in=20)
            if not title:
                raise exceptions.CommandError((Invalid URL, use a Youtube, SoundCloud or BandCamp link.', expire_in=20)        
        if 'entries' in info:         
                is_playlist = True
                try:
                    info = await self.downloader.extract_info(self.loop, song_url.strip('<>'), download=False, process=False)
                except Exception as e:
                    raise exceptions.CommandError("Could not extract info from input url\n%s\n" % e, expire_in=25)

                if not info:
                    raise exceptions.CommandError("Could not extract info from input url, no data.", expire_in=25)

                if not info.get('entries', None):
                    # TODO: Retarded playlist checking
                    # set(url, webpageurl).difference(set(url))

                    if info.get('url', None) != info.get('webpage_url', info.get('url', None)):
                        raise exceptions.CommandError("This does not seem to be a playlist...", expire_in=25)
                    else:
                        return await self.cmd_anglaispldump(channel, info.get(''))

                linegens = defaultdict(lambda: None, **{
                    "youtube":    lambda d: 'https://www.youtube.com/watch?v=%s' % d['id'],
                    "soundcloud": lambda d: d['url'],
                    "bandcamp":   lambda d: d['url']
                })
    
                exfunc = linegens[info['extractor'].split(':')[0]]

                if not exfunc:
                    raise exceptions.CommandError("Could not extract info from input url, unsupported playlist type.", expire_in=25)
        
        if not is_playlist:    
            for url in self.autoplaylist:
                if song_url == url:
                    return Response("Song already present in the autoplaylist!", delete_after=30)
            self.autoplaylist.append(song_url)		
            write_file(self.autoplaylist_file, self.autoplaylist)
            self.autoplaylist = load_file(self.autoplaylist_file)
            return Response("**%s** has been added to the autoplaylist." % title, delete_after=30)
        
        else:            
            not_added = 0
            added = 0
            msg = await self.safe_send_message(channel, "Now processing...")
            for entry in info['entries']:                      
                    song = 'https://www.youtube.com/watch?v=%s' % entry['url']   
                    dont_add = False
                    if self.autoplaylist:
                        for url in self.autoplaylist:
                            if song == url:
                                dont_add = True
                                not_added += 1
                                break                     
                    if not dont_add:
                        self.autoplaylist.append(song)		
                        write_file(self.autoplaylist_file, self.autoplaylist)
                        self.autoplaylist = load_file(self.autoplaylist_file)
                        added += 1
                        
                        
        if added and not not_added:
            await self.safe_edit_message(msg, "I've added %s songs to the autoplaylist" % added, send_if_fail=True)
        elif added and not_added:
            await self.safe_edit_message(msg, "I've added {} songs, but {} was already in".format(added, not_added), send_if_fail=True)
        else:
            await self.safe_edit_message(msg, "Everything was already in the autoplaylist, no songs has been added", send_if_fail=True)
```
Well I admit it, it's ugly, but it works.

**Comment by TicWE** [comment]
Thanks a lot :)

**Comment by Zenrac** [comment]
I forgot to add
```
if not title:
                raise exceptions.CommandError((Invalid URL, use a Youtube, SoundCloud or BandCamp link.', expire_in=20)
```
but i've modified my comment now

**Comment by TicWE** [comment]
Hey @zenrac, this time I was wondering if we could add a vote to remove just like the skip command ? I mean everyone could use the command and some could instaremove with the right permissions

**Comment by TicWE** [comment]
Anyone else ? :/

**Comment by Zenrac** [comment]
try to make your own based on the cmd_skip command, we should not help you to modify your bot.
More informations about modifications : https://github.com/Just-Some-Bots/MusicBot/wiki/Modification

**Comment by Xylems** [comment]
@zenrac i am getting an error

NameError: name 'player' is not defined. I am running the review version with heavy edits, however anything pre-existing should still work. I have tried to copy/past the code and i tried to manually add the code same error.  Any help would be appreciated

Nevermind! never code tired :D Thanks all this works great!!!!

**Comment by Xylems** [comment]
@zenrac Ok this time i am stuck for real :)

Everything seems to be working just fine.. I can do !add Link and it adds it and if it exists it tells me it exists. etc.. the only thing it will not do is if i just do !add it does not add the currently playing song. It doesnt say anything.. nothing in log files... just absolutely nothing.

(i did modify pladd to just add so thats not the issue)

Any suggestions you may be able to provide would be greatly appreciated

**Pull request closed without merging**
