### PR TITLE
Adds 'autoplaylist' command to allow better autoplaylist manipulation

### LINKED ISSUE #1880: Command to remove a song from autoplaylist
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [x] Question

Is there a command that already do this? because i didn't saw one
If not, it would be great to add one

### PR DESCRIPTION
**Pull request by obi23lipnik**
After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [X] I have tested my changes on Python 3.5/3.6

----

### Description
This pull request would add 'unsave' and 'autoplaylist [+, -, add, remove]' commands;
Unsave command functions like save except doing the opposite and autoplaylist is a culmination of both functionalities. 

To avoid repeating code 'save' was also refactored.

Also some housecleaning was applied -- namely, adding "expire_in" to command error raises and "delete_after" to response returns.

### CODE REVIEW

**Comment by MattBSG** [comment]
Some has been implemented already. See 83c91e781791362f1ca27976fd0994863f664108

**Comment by obi23lipnik** [comment]
@MattBSG Yes I've branched from the review branch already including the url option, the pull request builds on that.

**Comment by MattBSG** [comment]
Alright, I see what you have done here. If the autoplaylist command also implements song removal (either current or link) what is the purpose of the unsave command?

**Comment by obi23lipnik** [comment]
Well, I quite like the idea that `save` has an anti-command:`unsave` ... Also `unsave` acts as a nice shorthand for `autoplaylist -` ... You recommend removing unsave?

**Comment by jayktaylor** [comment]
Hey - I'm all good with this addition, but there seems to be some element of redundancy in having three different commands that could be combined into one. I'd recommend merging `save` and `unsave` into `autoplaylist` and removing the two aforementioned commands.

**Comment by obi23lipnik** [comment]
I didn't dare remove `save`, but I added a todo https://github.com/Just-Some-Bots/MusicBot/pull/1544/files#diff-21faf5966eaac420f9225d643caf3a13R1359

**Comment by BabyBoySnow** [comment]
Hello, was curious if you are still active and can double check this to make sure everything looks right to you? Thanks.

**Pull request merged**
