### PR TITLE
Added lyrics command

### PR DESCRIPTION
**Pull request by mvmcjr**
Display lyrics from lyric wikia.
Commands are: !lyric or !lyrics

### CODE REVIEW

**Comment by sypion** [comment]
When using this command, it spams the lyrics and does not stop.

**Comment by sypion** [comment]
Absolutely love this though!

**Comment by mvmcjr** [comment]
@sypion Well, can you please tell me the song you're trying to get the lyrics to ? It maybe linked due to character limit and the split wont stop

**Comment by sypion** [comment]
Sure thing! Try “The Great Divide” by Rebecca Black.

**Comment by mvmcjr** [comment]
@sypion Sorry to bother you again, but could you please send a screenshot or something of sorts ? I couldn't reproduce it :(

**Comment by sypion** [comment]
No worries! Here's a short video: http://recordit.co/qiAA7SDbjP/

**Comment by mvmcjr** [comment]
@sypion I think it was conflicting commands since you're not using prefixes. Try it now please

**Comment by sypion** [comment]
It didn't work unfortunately. In case you need some more information, I'm using the bot from the `Review` branch; not the `Master` branch.

**Comment by sypion** [comment]
Trying it once more-- and it seemed to have fixed the issue. I just switched "lyric" and "lyrics" because it made more sense in the code and when reading. Thanks a bunch my friend!

**Comment by TicWE** [comment]
The command works well but when I get the lyrics (even if it works), I get "Failed to get lyric from" with the artist name at the end, kinda funny. (Though it only did it once)
But this time I get the lyrics from a different song :/

**Comment by mvmcjr** [comment]
@TicWE The lyrics wikia is kinda bad, I wish I found another one. The failed messages are from failed attempts. The way it works is scraping the search page and trying to get lyrics for every result and returns the first one

**Comment by mvmcjr** [comment]
Oops

**Comment by Zenrac** [comment]
Tested and it work for few songs, but a lot didn't work even if the lyrics are on the website, this issue is maybe from the part that the first link of the search is mustly a link for the artist wiki

**Comment by mvmcjr** [comment]
Could you please provide some songs name for me to debug @zenrac ? The lyricwikia module actually throws an exception if it fails to get the lyrics of a specific link, and the code runs through all the search results trying to find a valid lyrics and then print out the first one

**Comment by Zenrac** [comment]
Sure, this is an example.

https://www.youtube.com/watch?v=YqeW9_5kURI
The command don't worked
but it's the third result on the website:
image

**Comment by zenrac** [comment]
Maybe it's because it didn't work when the artist name have more than one word

**Comment by Zenrac** [comment]
I've modified + tested anew, and I got a weird result : 

print(item) ---> Major Lazer & DJ Snake:Lean On
print(item.split(':')[0]) ---> Major Lazer & DJ Snake
print(item.split(':')[1]) ---> Lean On
```
Traceback (most recent call last):
  File "E:\desktop\music\musicbot\bot.py", line 4718, in on_message
    response = await handler(**handler_kwargs)
  File "E:\desktop\music\musicbot\bot.py", line 3739, in cmd_lyrics
    lyrics = lyricwikia.get_lyrics(item.split(':')[0], item.split(':')[1])
  File "C:\Users\Zenrac\AppData\Local\Programs\Python\Python35-32\lib\site-packages\lyricwikia\lyricwikia.py", line 21, in get_lyrics
    raise Exception('Cannot download lyrics')
Exception: Cannot download lyrics
```

**Comment by Zenrac** [comment]
One more information that may help you : 
image

image

As you can see, it worked when i've removed a part of the artist float

Maybe you should add something that remove one word from the end each time the download fail.

**Comment by mvmcjr** [comment]
@zenrac Oh wow, thanks for your feedback ! Unfortunately it's pretty late here, but as soon as I wake up tomorrow I'll get to fix it.

**Comment by mvmcjr** [comment]
@zenrac Try it now, please.

**Comment by Zenrac** [comment]
This is my update for you code.
```
    async def cmd_lyrics(self, channel, player):
        if not player.current_entry:
            return Response("No song currently being played")
        
        await self.send_typing(channel)
        songsResults = self.searchSong(player.current_entry.title)

        for item in songsResults:
            name = item
            pos= None
            if '(' in name and not '[' in name: #optional it allows to remove the (hd) or (feat) from the title
                pos = name.index('(') 
            elif '[' in name and not '(' in name:
                pos = tiem.index('[')
            elif '(' in name and '[' in name:
                pos = min(name.index('['), name.index('('))
            if pos:
                item = item[0:pos]
            try:
                nameofthesong = item.split(':')[1] 
                nameofthesong = nameofthesong.split('/')[0]
            except:
                pass
            try:    
                nameofthesong = nameofthesong.split('`\\')[0] #fix the issue from lyricswikia
            except:
                pass
            try:    
                if nameofthesong not in player.current_entry.title: #check if it's not the good lyrics
                    print('Not the good song... ' + nameofthesong) #it will spam if you don't remove it
                    continue
            except:
                pass
            try:
                lyrics = lyricwikia.get_lyrics(item.split(':')[0], item.split(':')[1])    
                await self.safe_send_message(channel, "Lyric for " + item.split(':')[0] + " - " + item.split(':')[1])
                n = 1985
                for i in range(0, len(lyrics), n):
                    await self.safe_send_message(channel, "```" + lyrics[i:i+n] + "```")
                return Response(":thumbsup:")
            except:     #if it fails let's remove some part of the artist name
                print("[Lyrics] Failed to get lyric from " + item)
                try:
                    count = 0
                    artist = item.split(':')[0]
                    for element in artist.split(' '):  #how much words in the artist name
                        count += 1                      
                        artist = artist.split(' ')[0:-count] #remove word(s)
                        artist = ' '.join(artist)
                        try:    
                            lyrics = lyricwikia.get_lyrics(artist, item.split(':')[1])    
                            await self.safe_send_message(channel, "Lyric for " + artist + " - " + item.split(':')[1])
                            n = 1985
                            for i in range(0, len(lyrics), n):
                                await self.safe_send_message(channel, "```" + lyrics[i:i+n] + "```")
                            return Response(":thumbsup:")
                        except:
                            pass
                except:
                    continue 

        return Response("Could not find the lyric")`
```

I've added more check, and fixed my issue

**Comment by mvmcjr** [comment]
@zenrac Wow, great work and a big relief cause I have a love-hate relationship with python. Anyway added to the fork.

**Comment by Zenrac** [comment]
Thx!
I hope that the part which checks if it's the good song will work in all cases. Otherwise, if someone find some "bugs" I will try to modify a bit the code
Btw, it's a very ugly code, do not hesitate to make him more pythonic ;)

**Comment by Zenrac** [comment]
Now it can gives the lyrics if you specify an URL. I've removed some useless parts, and modified a bit, It's better now but still ugly. ^^'
```
    async def cmd_lyrics(self, channel, player, song_url=None):
        """
        Usage:
            {command_prefix}lyrics 
            {command_prefix}lyrics song_url

        Displays the lyrics of the current song, otherwise you have to specify an URL
        """ 
            
        if song_url:                
            try:
                info = await self.downloader.extract_info(player.playlist.loop, song_url, download=False, process=False)
                title = info.get('title', '')
            except:
                return Response("Cannot find the title, please ensure you URL is correct")
        elif not player.current_entry:
            return Response("No song currently being played, please specify an URL")        
        else:
            title = player.current_entry.title
        await self.send_typing(channel)
        songsResults = self.searchSong(title)

        for item in songsResults: 
            try:
                nameofthesong = item.split(':')[1] 
                nameofthesong = nameofthesong.split('/')[0]
            except:
                pass
            try:    
                nameofthesong = nameofthesong.split('`\\')[0]
            except:
                pass
            try:    #too much try/except to remove that /ru from lyricswikia
                if nameofthesong not in title:
                    print("%s was not the song you were looking for don't you ?" % nameofthesong)
                    continue
            except:
                pass
            try:
                lyrics = lyricwikia.get_lyrics(item.split(':')[0], item.split(':')[1])    
                await self.safe_send_message(channel, "Lyrics for " + item.split(':')[0] + " - " + item.split(':')[1])
                n = 1985
                for i in range(0, len(lyrics), n):
                    await self.safe_send_message(channel, "```" + lyrics[i:i+n] + "```")
                return
            except:      
                print("[Lyrics] Failed to get lyric from " + item)
                try:
                    count = 0 #don't mind me
                    artist = item.split(':')[0]
                    for element in artist.split(' '): 
                        count += 1                      
                        artist = artist.split(' ')[0:-count]
                        artist = ' '.join(artist)
                        try:    
                            lyrics = lyricwikia.get_lyrics(artist, item.split(':')[1])    
                            await self.safe_send_message(channel, "Lyric for " + artist + " - " + item.split(':')[1])
                            n = 1985
                            for i in range(0, len(lyrics), n):
                                await self.safe_send_message(channel, "```" + lyrics[i:i+n] + "```") #feel redundant
                            return 
                        except:
                            pass
                except:
                    continue 

        return Response("Could not find the lyric")
```

**Comment by mvmcjr** [comment]
@zenrac wow dude, I don't even know what to say. Great work 👍

**Comment by ButterKing215** [comment]
How do I add this my self, I have experience with coding. So I have no idea how to implement this feature into my music bot, please help.

**Comment by Zenrac** [comment]
You can simply download this feature here : https://github.com/tzhongyan/MusicBot/tree/e18878bc9b0c2e8081790833d49920ebb8c6b24f

**Comment by Xylems** [comment]
not sure this needs to go mentioned, however make sure you add libxml2-dev to the apk add command in the Dockerfile or you will get an error message about libxml not being installed.

**Comment by Xylems** [comment]
Make sure that you add libxml2-dev and  libxslt-dev to the review version Dockerfile on the apk add command or else you will get a failure when building.

**Comment by Zenrac** [comment]
btw, instead of `if nameofthesong not in title:`

`if nameofthesong.lower() not in title.lower():` is better.

**Comment by ButterKing215** [comment]
When I try to run the bot I get this error please help.
[Screenshot from Gyazo](https://gyazo.com/1c2dc6f3d5412021a22fd2a5720517f2)

**Comment by mvmcjr** [comment]
@ButterKing215 this does not seem related to this fork, maybe missing dependencies?

**Comment by buhhhrandon** [comment]
Got the bot to run fine with no errors, I type {command_prefix}lyrics / {command_prefix} lyrics song_url, the bot says it's typing a message, but then disappears after about 5 seconds and no lyrics come up. Any idea?

Do I need to add another dependency for Ubuntu? How and what do I do.

**Comment by Zenrac** [comment]
All changes : https://github.com/Just-Some-Bots/MusicBot/pull/1218/files

No traceback = Cannot help.

If you don't get any tracebacks, replace 
`except:` to
```
except Exception as e:
    print(e) 
```

**Comment by buhhhrandon** [comment]
Wait, i'm confused. Which one do I edit for except im so lost.

**Comment by Zenrac** [comment]
Every `except` in this changes

**Comment by buhhhrandon** [comment]
So every except needs to be Exception?

Sorry, it's very late for me and im kinda slow. :P You lost me at the "as e: print(e) part.

**Comment by Zenrac** [comment]
If nothing happen when you use a command it means that you've got an error somewhere.
In that case a traceback will be displayed on your terminal unless the error happened during a `try`, to display an error that happened during a `try`, you must replace 
```
except:
    pass #rip error
```
to 
```
except Exception as e:
    print(e) #print the error
```

Then you can try again your command and put your entire traceback here, so we will be allowed to help you.

**Comment by buhhhrandon** [comment]
https://gyazo.com/87662e53d28637d4a398c139088aba86

I've done except Exception as e, nothing happens. Here are my logs as well.

https://gyazo.com/e4f32839b53ce7bc8b2db9ef0e5927a5
Nothing under, thats it.

**Comment by buhhhrandon** [comment]
https://gyazo.com/082a81d4a444859fc2de661e35d29d10

This might help actually.

**Comment by Zenrac** [comment]
image
Means that you didn't add 
```
    def searchSong(self, song_name):
        print("[Lyrics] Song name: " + song_name)
        encondedsongname = urllib.parse.quote_plus(song_name)
        print("[Lyrics] Search url: " + encondedsongname)
        page = requests.get('http://lyrics.wikia.com/wiki/Special:Search?query=' + encondedsongname)
        tree = html.fromstring(page.content)
        songs = tree.xpath('//li[@class="result"]/article/h1/a/text()')
        return songs
```
to you code, did you add all the following changes ?
https://github.com/Just-Some-Bots/MusicBot/pull/1218/files

**Comment by buhhhrandon** [comment]
I have added the def searchSong, maybe if I can send you my bot.py file and take a glance at it? I believe I have everything done right.

**Comment by buhhhrandon** [comment]
Got it to work, just went ahead and copied everything and added my other commands back in.

**Comment by loobing** [comment]
i have an error

image

btw i am using the review branch

**Comment by loobing** [comment]
The codes have quite some error for me cause i am using the review branch it doesnt let me import lyricwikia and import requests

**Comment by ghost** [comment]
any way to fix this error?

File "C:\Users\Thomas\Desktop\Vee 1.3 (beta)\musicbot\bot.py", line 1646
    def searchSong(self, song_name):
                                   ^
IndentationError: unindent does not match any outer indentation level

**Comment by mvmcjr** [comment]
@TomTheMan2016 You have to reident the file, you could that online or a text editor

**Comment by Buggs02** [comment]
umm it wont let me import requests or lyricwikia what do i do to fix it ?

**Comment by cesarcamarena** [comment]
Is there a way for me to implement this feature into my discord bot?

**Comment by mvmcjr** [comment]
@cacamarena42 You can use the code on the fork, or just download it from [here](https://github.com/tzhongyan/MusicBot/tree/e18878bc9b0c2e8081790833d49920ebb8c6b24f)

**Comment by cesarcamarena** [comment]
Welp, I tried my best to make this feature work. It just keeps giving me the error of not finding the lyrics as previously stated in this thread earlier. Oh well.

**Comment by jayktaylor** [comment]
Closing this - for those who seek this feature, feel free to look on forks, but we're not going to implement it into the native version of the bot. Hooking into the MediaWiki API for search results is somewhat unreliable, and the lyrics wikia is by no means the best method of grabbing lyrics. There's also quite a big issue of using the requests library in the bot, which is blocking. As the MusicBot uses asynchronous code, requests is not recommended and async alternatives like aiohttp are recommended.

**Pull request closed without merging**
