### PR TITLE
Musicbot Improvements

### PR DESCRIPTION
**Pull request by ghost**
I have changed the skip command so it is two commands (forceskip) and (voteskip) the reason for this is because I have noticed problems with admins on servers instaskiping when trying to voteskip so I have split the command in two also changed the example_ files to replace skip  with voteskip when it auto generates the permissions and options files I also added a change log command called (update) that can be used by modders or the developers to say whats new with the bot and whats been changed.  I had gotten feedback from users to improve the musicbot also I would like to know your opinions on my work. I am posting a run-able version of the bot you are free to do what you want but its more your opinion on my work is what I would like to know. I look forward to the responds.  Note: forgive me for the google link the file was too large to send over github.
also again I'm new to github so forgive me

### CODE REVIEW

**Comment by ghost** [comment]
forgive me I'm following up I realized I can upload the files I feel silly now forgive me 
forgive me for doing this it refuses to upload the files so I will be giving the link to my fork of the project sorry for this I really am

https://github.com/Jellco/MusicBot

**Comment by ToppleKek** [comment]
Glad to see that you're using my code and calling it yours 👌

**Comment by ghost** [comment]
Topkek we worked on it together so it is technical both our code so I thought it would be ok to release it

**Comment by ghost** [comment]
so I'm not claiming full credit its partly yours however probably should have been better about saying that

**Pull request closed without merging**
