### PR TITLE
adding song to autoplaylist

### PR DESCRIPTION
**Pull request by pastafarianGit**
adding cmd_add to add link into autoplaylist text file

### CODE REVIEW

**Comment by Zenrac** [comment]
Duplicate, same idea here #1010 
And both are mixed in my comment above

**Comment by TicWE** [comment]
Is there any way to display the name of the song added in the message from the bot ?

**Comment by Zenrac** [comment]
info = await self.downloader.safe_extract_info(player.playlist.loop, song_url, download=False, process=False)
            title = info.get('title', '')

            #Verify proper url
            if not title:
                raise exceptions.CommandError('Invalid url. Please insure link is a valid YouTube, SoundCloud or BandCamp url.', expire_in=20)

and replace

`return Response('Added %s to autoplaylist" % title)`

btw, it's a .txt that gets read each times, you don't even need to "restart the bot"

For more information see the #that I've put before

**Comment by Limmek** [comment]
This is what i use.

    async def cmd_add(self, channel, player, author, permissions, song_url):
        """
        Usage:
            {command_prefix}add song_link

        Adds the song to the playlist.  If a link is not provided, the first
        result from a youtube search is added to the queue.
        """

        write_to_file = False
        lines = []
        song_url = song_url.strip('<>')
        auto_playlist = open(self.config.auto_playlist_file, 'r')
        info = await self.downloader.safe_extract_info(player.playlist.loop, song_url, download=False, process=False)
        title = info.get('title', '')

        if not title:
            raise exceptions.CommandError('Invalid url. Please insure link is a valid YouTube, SoundCloud or BandCamp url.', expire_in=20)
        
        for i, item in enumerate(auto_playlist, 1):
            if item == song_url:
                write_to_file = True
                break   

        if not write_to_file:
            lines.append("Added %s to autoplaylist by **%s**\n" % (title, author.mention))
            with open(self.config.auto_playlist_file, "a") as new_auto_playlist:
                new_auto_playlist.write("\n{}".format(song_url))
            new_auto_playlist.close()
        else:
            lines.append("Song exist in autoplaylist already.")

        message = '\n'.join(lines)
        return Response(message, delete_after=30)

**Pull request closed without merging**
