### PR TITLE
Loop playlist, repeat song, move songs within playlist

### PR DESCRIPTION
**Pull request by NowIveAwoken**
After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5.3 or higher
- [x] I formatted my code with black

----

### Description
Adds two commands to repeat the song or playlist and moving songs within the playlist with the move command.  I've tested it a bit and so far there have been no issues from the servers I've been running it in but no guarantees that it is bug free.

### CODE REVIEW

**Comment by AutumnClove** [comment]
Nice PR, will test it out later tonight, in the meantime we're asking that all new changes have black ran over them. `python -m pip install black` `python -m black {file/s}`

**Review by Nubstex — APPROVED** [review]

**Review by Sandoplay — COMMENTED** [review]
Loop works fine.

**Review by Alllen95Wei — COMMENTED** [review]
How about sending a message when `move` is successed?
Line 1757: `return Response("No. {0} has been move to No. {1}.".format(indexes[0]+1, indexes[1]+1), delete_after=30)`

**Comment by gunplar** [comment]
+1 on this. @srhinos do you still support this repo?

**Comment by BabyBoySnow** [comment]
can you merge the current review branch into this please so I can check this out and make sure everything works out. Look forward to adding these features!

**Comment by Jcodeerd** [comment]
- Is it intended that it keeps looping a song, even when it's skipped?
- `!help move` doesn't work

everything else LGTM

**Pull request merged**
