### PR TITLE
Docker: PyNaCl needs libsodium-dev

### PR DESCRIPTION
**Pull request by cocoastorm**
After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5/3.6

----

### Description
Turns out in the Dockerfile `libsodium-dev` is listed as a build dependency. So it's removed after the Dockerfile is finished building the Docker image. Python needs libsodium-dev to be installed in the image to [import nacl.secret properly (from Discord.py)](https://github.com/Rapptz/discord.py/blob/async/discord/voice_client.py#L59)

I wrongly assumed PyNaCl wasn't being installed with pip, but turns out manually importing `nacl.secret` leads to this error in the Docker image:

`Error loading shared library libsodium.so.23`

Adding `libsodium-dev` as a core dependency in the Dockerfile fixes the problem.

### Related issues (if applicable)
#841

### CODE REVIEW

**Comment by Hydrar** [comment]
I discovered this too yesterday, although you only need to add libsodium to the dependencies apk install, -dev is only needed for the build portion.
Also what is up with all these tons of commits for this simple pull request? Just found this since I was about to put one up myself

**Comment by cocoastorm** [comment]
I don't know actually! The pull request template mentioned how the review branch had to be based on it? Which was why I rebased my branch to be based on the review branch instead of the master branch.

If you want you can make your own PR and I'll close this one haha, since you mentioned how including libsodium itself without -dev part might be a better idea lol.

**Comment by jayktaylor** [comment]
The review branch is the branch we develop on which is why we ask that PRs target that branch.

**Comment by cocoastorm** [comment]
@jaydenkieran, hey is this PR okay? I'm a bit puzzled why all these commits came through. (Probably, because of my rebase) If I need to redo my PR I'm fine with that.

Thanks!

**Comment by vdeville** [comment]
Thanks !

**Pull request merged**
