### PR TITLE
Update Python versions

### PR DESCRIPTION
**Pull request by phknot**
After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `dev` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.9 or higher
- [x] I have ensured my code is formatted using [Black](https://github.com/psf/black)

----

### Description

The minimum Python version is bumped to 3.9 to fix compatibility with new code.

Where possible, we now try to use the latest Python version (3.12).

### Related issues (if applicable)
https://github.com/Just-Some-Bots/MusicBot/issues/2368

### CODE REVIEW

**Comment by itsTheFae** [comment]
I would suggest keeping 3.8 in this PR.  I've fixed my typing blunder with #2370  which will let it work again.  
Or at least its an option. :P

**Comment by phknot** [comment]
> I would suggest keeping 3.8 in this PR. I've fixed my typing blunder with #2370 which will let it work again. Or at least its an option. :P

Yeah I guess a maintainer can make a decision on how to proceed 👍

**Comment by BabyBoySnow** [comment]
By the way, as far as I know aiohttp a required dependency is still failing on build wheels on 3.12, I'm hoping they fix that soon. 
For the time being, I will continue backwards compatibility, until told otherwise from the code owners.

**Comment by phknot** [comment]
> By the way, as far as I know aiohttp a required dependency is still failing on build wheels on 3.12, I'm hoping they fix that soon. For the time being, I will continue backwards compatibility, until told otherwise from the code owners.

I tested all the versions by bumping the version in the Docker file and it ran just fine for all.python versions from 3.9 to 3.12 so I think that problem is fixed

**Comment by BabyBoySnow** [comment]
> I tested all the versions by bumping the version in the Docker file and it ran just fine for all.python versions from 3.9 to 3.12 so I think that problem is fixed

Using windows 10 22h2, I still fail the build wheel on 3.12.1. The "solution" is to install Microsoft C++ Build Tools. I don't like this as a solution though since it's a 4-6gb download, which is a lot for users who might not have a ton of space on a vps. It builds fine on 3.8-3.11 without the additional tools. So I don't think it's anything on our end in the project.

**Pull request closed without merging**
