### PR TITLE
Clear command

### PR DESCRIPTION
**Pull request by fjking171**
!clear for use by bot owner

### CODE REVIEW

**Comment by imayhaveborkedit** [comment]
You copy pasted the diff `+`s in.

**Comment by fjking171** [comment]
Whoops.

**Comment by Neddz** [comment]
This has an indentation problem in bot.py, line 493. The if statement.

**Comment by fjking171** [comment]
Line 493 wasn't edited: https://github.com/SexualRhinoceros/MusicBot/pull/26/files

**Comment by imayhaveborkedit** [comment]
https://github.com/SexualRhinoceros/MusicBot/commit/d3fd70e84a9eb40d705877a3a3a5864d6c452d4e

**Pull request merged**
