### PR TITLE
time and date based logging system

### PR DESCRIPTION
**Pull request by OzzyHelix**
After creating your pull request, tick these boxes if they are applicable to you.

- [ ] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [ ] I have tested my changes on Python 3.8 or higher
- [ ] I have ensured my code is formatted using [Black](https://github.com/psf/black)

----

### Description
I didn't like that the logs wrote over themselves so I made it so log files had dates and times in the file name and when the bot runs it deletes logs older than a week

### CODE REVIEW

**Comment by OzzyHelix** [comment]
this was my attempt to improve the logging system I figured I would share it with you guys upstream

**Comment by OzzyHelix** [comment]
I didn't mean to include my readme I'm trying to figure out how to exclude it

**Comment by OzzyHelix** [comment]
I will close and reopen

**Comment by BabyBoySnow** [comment]
you can add it to the .gitignore file

**Pull request closed without merging**
