### PR TITLE
add instaskip command, edit skip command

### PR DESCRIPTION
**Pull request by ktzr**
resolves ticket #1032 

instaskip will skip the song if the user has the appropriate permissions
skip will always start a vote to skip

this allows admins to cast a vote to skip without forcing the rest of the channel to go along with it

all changes are surrounded with "#edit"

### CODE REVIEW

**Comment by Soitora** [comment]
I, for one, would this appreciate feature.

**Comment by dshoreman** [comment]
I actually implemented a similar thing on my install recently. I had an issue which probably affects this PR too.

With instaskip, `player.current_entry` is no longer what you'd expect by the time it gets to returning the `Response`, so the message sent to the Discord channel is actually an error.

Here's my implementation for comparison. The main difference is assigning `player.current_entry.title` before actually skipping the song.

```python
    async def cmd_skipnow(self, player, channel, author, message, permissions, voice_channel):
        """  
        Usage:
            {command_prefix}skipnow
        Skips the current song without a vote.
        """

        if player.is_stopped:
            raise exceptions.CommandError("Can't skip! The player is not playing!", expire_in=20)

        if not player.current_entry:
            if player.playlist.peek():
                if player.playlist.peek()._is_downloading:
                    # print(player.playlist.peek()._waiting_futures[0].__dict__)
                    return Response("The next song (%s) is downloading, please wait." % player.playlist.peek().title)

                elif player.playlist.peek().is_downloaded:
                    print("The next song will be played shortly.  Please wait.")
                else:
                    print("Something odd is happening.  "
                          "You might want to restart the bot if it doesn't start working.")
            else:
                print("Something strange is happening.  "                                                                                                                                                 
                      "You might want to restart the bot if it doesn't start working.")

        now_playing = player.current_entry.title

        player.skip()  # check autopause stuff here
        await self._manual_delete_check(message)

        return Response(
            'your instaskip for **{}** was acknowledged. {}'.format(
                now_playing,
                ' Next song coming up!' if player.playlist.peek() else ''
            ),   
            reply=True,
            delete_after=30
        )
```

I also removed the `instaskip` option, though this is more specific to my use case. `!instaskip` is only granted to the moderators group, negating the need to also check for the `instaskip` option: if someone can use the command, they're inherently able to instaskip.

**Comment by ghost** [comment]
This is the Code I've added to my fork of the of the bot I hope it helps but this is what I've done and I had help from someone named topkek. me and topkek removed the need for a permission based skip command there are now two separate forceskip and voteskip. they do as the name says forceskip skips a song and voteskip votes to skip a song these two commands would replace the skip command all together and you can give admins access to the forceskip command and have them use it as a way to bypass a song if it is not suppose to be played forgive me I posted it as new comment but I feel its fairly useful #edited

**Comment by ghost** [comment]
async def cmd_forceskip(self, channel, author, user_mentions, player, message):
        """
        Usage:
            {command_prefix}forceskip
        Force skip command is used to skip songs that should not be playing
        """

        if player.is_stopped:
            raise exceptions.CommandError("Can't skip! The player is not playing!", expire_in=20)

        if player.is_paused:
            raise exceptions.CommandError("Can't skip! The player is paused!", expire_in=20)

        if not player.current_entry:
            if player.playlist.peek():
                if player.playlist.peek()._is_downloading:
                    # print(player.playlist.peek()._waiting_futures[0].__dict__)
                    return Response("The next song (%s) is downloading, please wait." % player.playlist.peek().title)

                elif player.playlist.peek().is_downloaded:
                    print("The next song will be played shortly.  Please wait.")
                else:
                    await self.safe_send_message(channel, "The Musicbot has stopped responding")
            else:
                await self.safe_send_message(channel, "Something strange is happening, do restart to fix this")

        if player.is_playing:
            player.skip()
            await self._manual_delete_check(message)
        if player.is_playing:
             return Response('The song was force skipped by `%s`' % author.name, delete_after=35)


    async def cmd_voteskip(self, player, channel, author, message, permissions, voice_channel):
        """
        Usage:
            {command_prefix}voteskip
        Skips the current song when enough votes are cast, or by the bot owner.
        """

        if player.is_stopped:
            raise exceptions.CommandError("Can't skip! The Bot is not playing!", expire_in=25)

        if not player.current_entry:
            if player.playlist.peek():
                if player.playlist.peek()._is_downloading:
                    # print(player.playlist.peek()._waiting_futures[0].__dict__)
                    return Response("The next song (%s) is downloading, please wait." % player.playlist.peek().title)

                elif player.playlist.peek().is_downloaded:
                    print("The next song will be played shortly.  Please wait.")
                else:
                    print("Something odd is happening.  "
                          "IT FUCKED UP RESTART THE BOT.")
            else:
                print("Something strange is happening.  "
                      "You might want to restart the bot if it doesn't start working.")

        # TODO: ignore person if they're deaf or take them out of the list or something?
        # Currently is recounted if they vote, deafen, then vote

        num_voice = sum(1 for member_is in voice_channel.voice_members
                        if not (member_is.deaf or member_is.self_deaf))

        num_skips = player.skip_state.add_skipper(author.id, message)

        skips_remaining = min(self.config.skips_required,
                              sane_round_int(num_voice * self.config.skip_ratio_required)) - num_skips

        if skips_remaining <= 0:
            player.skip()  # check autopause stuff here
            return Response(
              'your skip for **{}** was acknowledged.'
                '\nI guess the vote to skip has been passed.{}'.format(
                    player.current_entry.title,
                    ' Next song coming up!' if player.playlist.peek() else ''
                ),
                reply=True,
                delete_after=20
            )

        else:
            # TODO: When a song gets skipped, delete the old x needed to skip messages
            return Response(
                'Your skip for **{}** was acknowledged.'
                '\n**{}** more {} required to vote to skip this song.'.format(
                    player.current_entry.title,
                    skips_remaining,
                    'person is' if skips_remaining == 1 else 'people are'
                ),
                reply=True,
                delete_after=20
          )

**Comment by ghost** [comment]
I would love to hear feedback on this

**Pull request closed without merging**
