### PR TITLE
updated bot.py to call change_presence as change_status is deprecated.

### PR DESCRIPTION
**Pull request by ghost**
Get rid of annoying "change_status is deprecated" coroutines message by switching to change_presence.

### CODE REVIEW

**Comment by FIERCEDINO080** [comment]
So, I'm guessing this fixes this problem where it doesn't show a status message on the bot, right?

**Comment by ghost** [comment]
Nah, it just prevents a deprecation message from being displayed in the bot's console output when change_status is called by calling change_presence instead. change_status was deprecated as of [discord.py v0.13.0](http://discordpy.readthedocs.io/en/latest/whats_new.html#v0-13-0).

**Comment by FIERCEDINO080** [comment]
oh ok :(

**Comment by jayktaylor** [comment]
This issue was resolved in https://github.com/Just-Some-Bots/MusicBot/commit/ee8be2ac6af305a79b55cc51f4ddf29f2a6232bf.

**Pull request closed without merging**
