### PR TITLE
Added cmd_remove (removes a song from the queue based on index)

### PR DESCRIPTION
**Pull request by aegpoadan**
Remove command allows a user to remove a song from the "to-be-played" queue based on the song's index. Plan to add "remove song by name" feature in the future.

### CODE REVIEW

**Comment by KingGold171** [comment]
https://github.com/CArchetype/MusicBot/commit/ddb842794fcc20003ac24b380bed1b8ef418553c

**Comment by aegpoadan** [comment]
I figured this functionality had already been done by someone. Just curious, why hasn't that remove command made it to the release version of MusicBot?

**Review by MattBSG — CHANGES_REQUESTED** [review]
Update for compatibility with 1.9.6 and remove profanity from responses

**Comment by MattBSG** [comment]
#568 Was merged

**Comment by Trahloc** [comment]
Would it be possible to make "remove 0" delete the current playing song since there isn't any way to go to the previous song so that the current song is queue 1 and there isn't any way to list queues larger than 10 (at least help queue is useless on that front) so that you can find out what the number for the current song is so you can "remove 578"?

**Comment by MattBSG** [comment]
@Trahloc `remove 0` would be unnecessary since the current playing song is removed with `skip` (Auto skip for owner). The multiple queue pages is something I’ve been wanting to do, like paginating with reactions for input. Haven’t gotten anything worthy of commuting though, so it is good to hear that is wanted.

**Pull request closed without merging**
