### PR TITLE
Re-order and add 18.04 Ubuntu guide

### PR DESCRIPTION
**Pull request by AleanaA**
After creating your pull request, tick these boxes if they are applicable to you.

- [ ] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [ ] I have tested my changes on Python 3.5/3.6

----

### Description
Re-orders the Ubuntu versions from 18.04 to 14.04 and adds an 18.04 guide.

### CODE REVIEW

**Comment by jayktaylor** [comment]
I'd usually merge this, but I'm just wondering... maybe there's a way we can make it so that we don't have to make a guide for every Ubuntu version? Or at least, a better way of having them on a page rather than having the instructions all crammed all over the place in `ubuntu.md`. Any ideas?

**Comment by AleanaA** [comment]
I mentioned in the VIP channel on the help server that i wanted to use dropdowns instead to reduce the clutter, but codeblocks won't work in them on the site @ https://aleanaa.github.io/MusicBot/installing/ubuntu/

**Comment by AleanaA** [comment]
@jaydenkieran Out of curiosity, is the 14.04 guide still needed? 14.04 is End of Life early next year, and I feel like just having guides for the latest two LTS releases in `ubuntu.md` would be fine.

**Comment by MattBSG** [comment]
My two cents is no, it's not. However, as long as the bot *works* on 14.04 we should mark it as unsupported in the guides instead for those who may have legacy systems

**Comment by AleanaA** [comment]
Hmm... So possibly a Legacy tab in the guides list? This would work for things such as CentOS as well for whenever CentOS 6 is EOL, and 8 is released.

**Comment by jayktaylor** [comment]
+1 for marking 14.04 guide as unsupported/legacy

**Comment by jogerj** [comment]
~~This won't work:
ppa:mc3man/xerus-media~~

~~Cannot add PPA: ''This PPA does not support bionic''.~~
> @jogerj The 18.04 guide I wrote doesn't add that ppa, or any for that matter.
> 
> This thread also isn't for support with the guides, it's for implementing an Ubuntu 18.04 guide, and moving or removing the 14.04 guide.

My bad, read the wrong lines.

Btw I'm running Linux Mint 19 (based on Ubuntu 18.04) I just used debian guide to run the bot and it works fine.

**Comment by AleanaA** [comment]
@jogerj The 18.04 guide I wrote doesn't add that ppa, or any for that matter.

This thread also isn't for support with the guides, it's for implementing an Ubuntu 18.04 guide, and moving or removing the 14.04 guide.

**Pull request merged**
