### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Jcodeerd**
After creating your pull request, tick these boxes if they are applicable to you.

- [V ] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [V ] I have tested my changes on Python 3.5.3 or higher (3.7)

----

### Description

I updated requirements.txt to the newest versions of the deps.

### Related issues (if applicable)

everything with the `deny-new` error

### CODE REVIEW

**Comment by Jcodeerd** [comment]
BTW: this is also meant to merge into Review :)

**Comment by AleanaA** [comment]
Pull requests should target Review in the pull request, commenting that they are meant to be merged is not proper PR format, nor is that how PR's work.

**Comment by Jcodeerd** [comment]
oh, sorry 'bout that, I will make one to target review

**Comment by AleanaA** [comment]
#2103 Already does this.

**Pull request closed without merging**
