### PR TITLE
bot larsbot

### PR DESCRIPTION
**Pull request by nielsen223**
bot larsbot

After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [ ] I have tested my changes on Python 3.5/3.6

----

### CODE REVIEW

**Comment by AleanaA** [comment]
Uh?
What's this pr supposed to even be?

**Comment by nielsen223** [comment]
+play +do  +artoplay

**Comment by nielsen223** [comment]
jyjry

**Comment by MattBSG** [comment]
This repository is for a musicbot, so I’m really confused on what you mean. This isn’t a remotely valid PR either. If you have questions about the bot feel free to join our support server https://discord.gg/bots

**Pull request closed without merging**
