### PR TITLE
[FIX] fix slow dowload speed

### PR DESCRIPTION
**Pull request by TxMat**
After creating your pull request, tick these boxes if they are applicable to you.

- [ x ] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [ x ] I have tested my changes on Python 3.5.3 or higher

----

### Description
switching to yt_dlp instead of youtube_dl to fix the downloading speed cap

### Related issues (if applicable)
#2257

### CODE REVIEW

**Comment by TxMat** [comment]
yeah sorry about the commit list but i reforked the project after them so the only thing modified is the dependancy

**Comment by AleanaA** [comment]
You may want to re-review the PR you've made, specifically looking at the Files Changed section o.o;

**Comment by TxMat** [comment]
yeah i'll make a clean pr sorry about that

**Comment by AleanaA** [comment]
There's other issues with the simple swap to yt_dlp as of now anywho, I'm working on fixing the kinks that yt-dlp causes, such as ignoring the yt-dl options and downloading outside the audio_cache folder and then trying to get a PR up with everything working:tm:

**Comment by TxMat** [comment]
perfect

**Pull request closed without merging**
