### PR TITLE
first merge

### PR DESCRIPTION
**Pull request by OzzyHelix**
After creating your pull request, tick these boxes if they are applicable to you.

- [ ] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [ ] I have tested my changes on Python 3.8 or higher
- [ ] I have ensured my code is formatted using [Black](https://github.com/psf/black)

----

### CODE REVIEW

**Comment by OzzyHelix** [comment]
sorry thought I was updating on my fork

**Comment by BabyBoySnow** [comment]
lol all good. Was really confused at first haha.

**Comment by OzzyHelix** [comment]
I'm maintaining a fork because I have modded this bot to service a particular purpose I just figured I could use a fork to keep my modded bot updated

**Comment by OzzyHelix** [comment]
I don't intend to share it or anything I just want to keep my modded version update to date with upstream code

**Pull request closed without merging**
