### PR TITLE
Update User-Agent

### PR DESCRIPTION
**Pull request by amit177**
After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5.3 or higher

----

### Description

The bot was not set to use a User-Agent when sending out requests.
This caused some websites to block the bot as it was considered malicious.
In addition to that, the header was changed to be just the bot's version instead of including the default headers (discordbot, python, etc), this was done because the header `aiohttp` is considered malicious by some websites.

### Related issues (if applicable)

#2190

### CODE REVIEW

**Comment by Jcodeerd** [comment]
Why remove pip and pynacl from requirements.txt?

**Comment by amit177** [comment]
They weren't removed in this PR, the commit was just merging my review branch with the current review branch.

**Review by AleanaA — APPROVED** [review]

**Comment by AleanaA** [comment]
I'd personally wait for @srhinos to approve before a merge due to the formatting changes, as I know there have been recent moves to stick to Black formatting (#2182 #2184)

**Review by TheerapakG — APPROVED** [review]

**Review by srhinos — CHANGES_REQUESTED** [review]
Please run Black on your code w/ line length of 99!

**Comment by amit177** [comment]
@srhinos

**Review by srhinos — APPROVED** [review]
Looks good thanks for making that change!

**Pull request merged**
