### PR TITLE
ci: refactor docker builds

### LINKED ISSUE #2412: Add Docker image documenation and default Docker registry.
### What new feature would you like to see?

Docker container image documentation and a default registry to pull it from, such as Docker Hub?

### Which of these categories fit your request?

Other

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

### PR DESCRIPTION
**Pull request by pythoninthegrass**
After creating your pull request, tick these boxes if they are applicable to you.

- [ ] I have tested my changes against the `dev` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.8 or higher
- [ ] I have ensured my code is formatted using [Black](https://github.com/psf/black)

----

### Description

- ~~`README.md`: fixed markdown formatting, added html todo list for container registry info, documented changes~~
- `docker.yml`: build amd64 and arm64 images, then push to container registries (tested GitHub Container Registry and Docker Hub)
- `Dockerfile`: buildkit syntax, formatting, pip and python env vars, and optional label (used with gha)
- `docker-compose.example.yml`: refactored for implicit or unset directives based on `Dockerfile`
- `docker-entrypoint.sh`: get posix `sh` from `env`, remove bashisms, double quote cli args to avoid word splitting
- `.dockerignore`: added relevant files to ignore
- `.dive-ci`: analyzes docker images
- `.hadolint.yaml`: added to lint Dockerfiles
- `.gitignore`: added relevant files to ignore, annotated sections, added inclusions at the end
- `.env.example`: added to provide an example of the environment variables for docker compose builds
- ~~`.editorconfig`: added to enforce consistent coding styles between different editors and IDEs~~

### Related issues (if applicable)

Closes #2412

### CODE REVIEW

**Comment by BabyBoySnow** [comment]
I'll review further in the morning, (it's 3am for me as I type this) some things to note though. PR's must target the `dev` branch, which unfortunately led to a lot of conflicts. 
The editor config I won't accept, black should handle our needs well enough and is the same format d.py uses. The readme changes, should really be going to the gh-pages, not on here as the readme here is just intended for a quick overview, the gh-pages contain the guides.

**Comment by itsTheFae** [comment]
You should base these changes off of the dev branch instead of master.  It should resolve the conflicts and will make review of the changes much easier.    

As Snow mentioned, the documentation parts will need to be a separate PR into the `gh-pages` branch of the repo.  
For that I would suggest making a file at `_docs/installing/docker.md` and putting the related documentation there.  
We're working on updating docs at the moment, so a new file should make it easy to pull into those up coming changes.  

Thanks!

**Comment by BabyBoySnow** [comment]
I've merged dev into this pr, which should address the merge conflicts. Other than that please look into the requested changes and suggestions from Fae and myself. Thank you!

**Comment by itsTheFae** [comment]
@BabyBoySnow That merge might have clobbered some edits...  It may be better to make a new PR at this point.  
The `musicbot.service` file was recently removed from dev with the latest installer updates.  

If this PR is cleaned up, it must be squash-merged or it'll make a mess of commit history.  

@pythoninthegrass For future PRs, I would suggest making changes in a new branch.  As it stands now, some commit history may be lost when this gets squashed and you later sync your master branch with this repo.

**Comment by pythoninthegrass** [comment]
Removed .editorconfig and reset the readme. Do you want to continue this PR or create a new one with a feature branch on my fork?

Will open a `_docs/installing/docker.md` PR after this is approved.

**Comment by pythoninthegrass** [comment]
> The editor config I won't accept, black should handle our needs well enough and is the same format d.py uses.

FYI black only covers python. Looking at the commit history here, you shouldn't be so quick to dismiss something used by much bigger projects.

**Comment by itsTheFae** [comment]
Lets do a new branch and a new PR.  Keeps it all clean, simple, and all on-scope.    
Thanks again!

**Pull request closed without merging**
