### PR TITLE
Dpy rewrite

### PR DESCRIPTION
**Pull request by rnegrin90**
After creating your pull request, tick these boxes if they are applicable to you.

- [❎] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [✅] I have tested my changes on Python 3.5/3.6

----

### Description

I was unsure about what is the focus for the rewrite so I tried running it, saw a bunch of things blowing up and tried to fix them one by one.

Before, the bot was able to play a song, but it would not add anything to the queue or play the next song.

I have fixed a few commands, but the `autoplaylist` is still misbehaving, and is not currently deleting the messages after the set time (although is not throwing an exception anymore)

Let me know if there is anything specific you want to me to focus on for the next commits.

### CODE REVIEW

**Comment by MattBSG** [comment]
The review branch is our development branch. Do not run dpy-rewrite: it is not nearly finished and is only used for compatibility with the new discord-py rewrite, it’s the exact same as the review branch otherwise.

**Comment by rnegrin90** [comment]
My intention was to help on the compatibility with the discord-py rewrite 😋 nothing on this PR is useful?

**Comment by jayktaylor** [comment]
While the general public shouldn't be using the dpy-rewrite branch (which is probably why Matt closed hte PR), I'm open to developers making contributions to help fix code that has changed from the current version of discord.py to the rewrite version. I'll look through this.

**Comment by jayktaylor** [comment]
I just looked over the changes and tested them. I'll probably make some additional fixes, but this is helpful and cuts down on the work I need to do. Thanks. Feel free to make another PR if you fix anything else.

**Comment by MattBSG** [comment]
I was also on mobile and mistook this for an issue and someone trying to run it (maybe on d-py async branch), so I apologize and appreciate the PR.

**Comment by rnegrin90** [comment]
Thank you guys! I'll will be making more changes when I have time ;)

**Pull request merged**
