### PR TITLE
Add Autoplay feature

### PR DESCRIPTION
**Pull request by ekrekeler**
Adds a command to enable and disable the use of the autoplaylist from the discord chat.

### CODE REVIEW

**Comment by sypion** [comment]
[This was done previously.](https://github.com/Just-Some-Bots/MusicBot/pull/900)

**Comment by ekrekeler** [comment]
Yes I know, but that fork is outdated and throws an error if there are no songs in the playlist.

**Comment by DevanFischer** [comment]
this may be a silly question but is there a way for me to pull these changes and automatically merge them into my file?

**Comment by Zenrac** [comment]
@ekrekeler What kind of error did you get ?

**Comment by toxicRavioli** [comment]
please help
`[Command] 247182525171105795/Toxic (r!autoplay)
Traceback (most recent call last):
  File "/var/www/ravioli/musicbot/bot.py", line 2349, in on_message
    response = await handler(**handler_kwargs)
  File "/var/www/ravioli/musicbot/bot.py", line 1712, in cmd_autoplay
    elif self.use_auto_playlist:
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 264, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'musicbot.bot.MusicBot'>' object has no attribute 'use_auto_playlist'`
thanks in advance

**Review by MattBSG — DISMISSED** [review]
Please resolve conflicts and confirm working with latest review branch

**Comment by MattBSG** [comment]
Fully implemented in commit e32cf93f871a61c3fe65a752b447911e22c1e4e8 at https://github.com/Just-Some-Bots/MusicBot/blob/review/musicbot/bot.py#L2234

**Pull request closed without merging**
