### PR TITLE
Add logging to a file & Discord channel(s)

### PR DESCRIPTION
**Pull request by jayktaylor**
**Works with MusicBot version `1.9.5_2`**

> **Note:** This PR was previously purely for posting fancy messages to Discord channels with important information. I have rewritten and expanded on the code to allow it to be more extensive.

This pull request enables **logging**. It rewrites most of the `print()` functions to use a `log()` function, which can print to console (if necessary), writes to a file (if enabled, see below) and posts to Discord channels (if enabled, see below).

Configuration for this mechanic of the bot is done in the `logging.ini` file inside the `config` folder:
- **File** (boolean) - Enable/disable logging to a file (`bot.log`)
- **Channels** (list) - List of Discord channel IDs to send logs to
- **TimeFormat** (string) - Overwrite the default time format for the logs

The file clears itself on every bot start if the feature is enabled in the first place.
# Examples
## File

File
## Discord

Discord

### CODE REVIEW

**Comment by jaydenkieran** [comment]
As @imayhaveborkedit wanted to get it working with multiserver support, I have pushed changes that allow for this. The config options have changed slightly.

Rather than `LoggingChannel`, there are now two variables.

- `LogMasterChannel` - **Channel ID** - All logs will go here if it has an entry. This allows for a central administrator/developer to see what is going on in all servers the bot is a part of.
- `LogSubChannels` - **List of Channel IDs** - These channels receive events for their **own server only**.

Here's how it looks:

**Master channel example**

Master logs

**Sub channel example**

Sub logs

Any information logged to the master channel, other than the bot initializing, will show the server that the event happened in.

**Comment by Loafabreadly** [comment]
Man this looks awesome hope it gets merged :D

**Comment by jaydenkieran** [comment]
## Changes since last comment
I pretty much made changes to further negate the need for constantly checking the console.
 
- Now logs when the bot joins or leaves a server using `on_server_join` and `on_server_leave` events
- Now logs attempts to delete audio cache
- Fixed to allow for automatic merging with base branch again
- Now logs when the client fails to join an "autojoin" channel with exception
- References to "MusicBot" are now replaced with the bot's username
- Now logs when the client attempts to and establishes a voice connection

If anything else **needs** to be logged I'll add it in, but for the current state of the bot this should do.

**Comment by jaydenkieran** [comment]
Updated yesterday to resolve merge conflicts. 

# Roadmap

Planning to implement these today or tomorrow to clean things up a bit. 

- [ ] Reformat how logs are displayed
- [ ] Allow configuration of date format
- [ ] Remove autojoin logging, un-needed as all voice connections are logged now
- [ ] Permissions checks for sending messages to a logging channel
- [ ] Redo configuration options

**Comment by jaydenkieran** [comment]
**Updated** - 12th May

Made a bunch of changes today that should pave the way towards being officially implemented within the bot. I've included an overview of the changes below.

- :tada: **Improved logging function**
    - Before, the logging was done via two different functions called `log_to_master` and `log_to_channel`. This was un-needed. I merged them both into one function, `log`. Additionally, this commit removes logging of autojoining (voice connections are logged regardless, we don't need another logged message for the same thing), and changes the formatting of most messages.
- :tada: **Handling for incorrect IDs in config**
    - It came to my attention recently that the bot wouldn't execute commands while using the logging PR. Having looked into it, I debugged the issue to be down to incorrect master/subchannel IDs not being caught. I've implemented checks for this now, and took appropriate action when the bot can't find one of the text channel.
- :alarm_clock: **Time format configurable**
    - One of the requested features on Discord (thanks Kiyah) was to allow for configuration of the date shown on startup. I didn't really see a use for that (so I removed the date showing altogether), though it made me think it'd be nice to let users configure the format of the time displayed in all log messages via the configuration.
- :house: **Log region changes**
    - As you could work out from the title, changes to a server's region (which causes the bot to reconnect to the voice client) are now logged.
- :inbox_tray: **Log youtube-dl downloads**
    - I added code to log downloads (shown as `[Download] Started: ____` in console) in the master channel only. This is, like the rest of the logging features, configurable in the options file.

Here are the changes to `options.ini`:

- :wrench: `LogMasterChannel` is now just `MasterChannel`
- :wrench: `LogSubChannels` is now just `SubChannels`
- :wrench: `LogExceptions` is now just `Exceptions`
- :wrench: `LogQueue` and `LogCommands` are now `Interactions`
- :heavy_plus_sign: Added `Downloads` to enable download logging
- :heavy_plus_sign: Added `TimeFormat` to customize displayed time format

Example

_Example of a master channel after this update_

**Comment by ImthePeach** [comment]
I do like this a lot actually, reminds me of rh1's log channels. Definitely for the people who want to know everything their bot is doing.

**Comment by deansheather** [comment]
@imayhaveborkedit you have any opinion on this?

**Comment by imayhaveborkedit** [comment]
No.  I'm going to ignore it until I have my own internal logging system setup.

**Comment by deansheather** [comment]
:+1:

**Comment by jayktaylor** [comment]
Closing this pull request. As of commit https://github.com/SexualRhinoceros/MusicBot/commit/1623506d2089a2d8d5a533299a6225d294c2f7a1, an implementation of logging was added to the MusicBot. Not sure whether Bork plans to allow logging to a Discord channel.

**Pull request closed without merging**
