### PR TITLE
Add option for the bot to stay online

### PR DESCRIPTION
**Pull request by Maskarada**
Is there some possibility that you add an option for the Music BOT to stay online even when your PC is turned off?

### CODE REVIEW

**Comment by imayhaveborkedit** [comment]
I don't even.

**Comment by Maskarada** [comment]
Sorry if I asked something stupid... x.x

**Comment by ImthePeach** [comment]
You made a pull request for a question? lol.
Bot doesn't work like that, the bot runs through your computers cmd, if you turn it off or put it to sleep it cancels the operations of the cmd because well, the computer isn't running then. If you wan't it to stay on 24/7 get a VPS or leave your computer on 24/7.

**Comment by Maskarada** [comment]
Sorry man! I really use this website for the first time! Didn't know how it
works! I made a pull request cause I had no idea what I'm doing! And I
understand now :) it's quite logical, but oh well, had to ask! The bot is
awesome BTW and very flexible! Continue your awesome work!

**Pull request closed without merging**
