### PR TITLE
Added queue repeat functionality

### PR DESCRIPTION
**Pull request by elenashen2010**
Added a new Repeat option to enable queue looping.
!repeat command toggles it on and off
!queue now shows the status of the repeat option

### CODE REVIEW

**Review by MattBSG — CHANGES_REQUESTED** [review]
If this is updated with the current version of the review branch then we can look to move forward with this. Otherwise this is so outdated with the last commit in 2016 that I'll close this if there is no activity soon since it is going to be a battle to pull a lot of this to the new code base and resolves all the conflicts.

**Comment by cordlessvii** [comment]
Is this a current feature? I'm trying to figure out how to loop a youtube playlist without autoplayist (can't be random)

**Comment by MattBSG** [comment]
@cordlessvii No. This is not currently implemented.

**Comment by cordlessvii** [comment]
@mattbsg thank you for the quick response. Is there anything i can do to have a feature like this? The auto playlist works but it randomizes the list. Is there a way I can loop a playlist or set the autoplaylist to not random? Thanks again

**Comment by MattBSG** [comment]
@cordlessvii We can only ship features that are actually made obviously, so feel free to send a a PR with updates, but if you don’t know how, there is a feature in the review branch to play the autoplaylist in order. So you use the review branch or wait until the next version release depending on how much of importance this is to you (make sure to reconfigure the bot from scratch if you use review so you get the updated options.ini file).

**Comment by cordlessvii** [comment]
@MattBSG I downloaded the review branch and reconfigured the options.ini as you mentioned. I saw the option for AutoplaylistRandom and marked it as no, but it still plays random. Any ideas or something I'm doing wrong? I'm hosting this on heroku so I had to copy over the runtime.txt and Procfile from the master branch.

Also, I'm able to run the review branch bot locally on my computer (still plays autoplaylist random though) and when I try to host it on heroku I get the error message below, even though I did install it through Git.

2018-02-10T15:08:22.529417+00:00 app[worker.1]: [CRITICAL] launcher: Bot wasn't installed using Git. Reinstall using http://bit.ly/musicbotdocs.
2018-02-10T15:08:22.529595+00:00 app[worker.1]: Press enter to continue . . .Traceback (most recent call last):
2018-02-10T15:08:22.529601+00:00 app[worker.1]:   File "run.py", line 421, in <module>
2018-02-10T15:08:22.529917+00:00 app[worker.1]:     main()
2018-02-10T15:08:22.529923+00:00 app[worker.1]:   File "run.py", line 332, in main
2018-02-10T15:08:22.530212+00:00 app[worker.1]:     sanity_checks()
2018-02-10T15:08:22.530214+00:00 app[worker.1]:   File "run.py", line 198, in sanity_checks
2018-02-10T15:08:22.530328+00:00 app[worker.1]:     req_ensure_env()
2018-02-10T15:08:22.530334+00:00 app[worker.1]:   File "run.py", line 282, in req_ensure_env
2018-02-10T15:08:22.530511+00:00 app[worker.1]:     bugger_off()
2018-02-10T15:08:22.530517+00:00 app[worker.1]:   File "run.py", line 182, in bugger_off
2018-02-10T15:08:22.530694+00:00 app[worker.1]:     input(msg)
2018-02-10T15:08:22.530729+00:00 app[worker.1]: EOFError: EOF when reading a line

**Comment by MattBSG** [comment]
@cordlessvii Heroku won’t work with the bot well, that message about the environment check is also because you need to download with git not from the web view. If you need more support hop on into our discord server and give me a ping today and I’ll pop in to help. https://discord.gg/bots

**Comment by cordlessvii** [comment]
@MattBSG thanks man, I'm in the server now. What's your name on there or you can message me @cordlessvii#3722

**Comment by MattBSG** [comment]
Closing due to inactivity.

**Pull request closed without merging**
