### PR TITLE
Add playnext command to bot.py (#786)

### PR DESCRIPTION
**Pull request by dannytb**
cmd_play is now _cmd_play and takes an additional flag. The flag is used
by the new cmd_play and cmd_playnext to determine which side of the
playlist songs get added to. Songs get added to the front of the queue
if the flag, "head", is true, otherwise they get added to the back of
the queue.

After creating your pull request, tick these boxes if they are applicable to you.

- [X] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [X] I have tested my changes on Python 3.5/3.6

----

### Description
This is a feature requested in #786. The playnext command functions the same way as the play command except the song gets added to the front of the playlist, instead of the back. The code for the play command was moved into a "_cmd_play" function, which is now called by both the new play command and the playnext command, to avoid duplicate code.

### Related issues (if applicable)
#786

### CODE REVIEW

**Comment by lsr4556** [comment]
i don't know why but it's adding songs twice everyta time I call play or playnext :/

**Comment by vStone** [comment]
> 
> 
> i don't know why but it's adding songs twice everyta time I call play or playnext :/

The original add_entry is also still there. Perhaps this is the issue:

https://github.com/Just-Some-Bots/MusicBot/pull/1579/files#diff-54341ae181d3fc4d74a37217d1676aa9c3e7576bf63654d91deff9a5d8d9d05bR1589

**Comment by AutumnClove** [comment]
> > i don't know why but it's adding songs twice everyta time I call play or playnext :/
> 
> The original add_entry is also still there. Perhaps this is the issue:
> 
> https://github.com/Just-Some-Bots/MusicBot/pull/1579/files#diff-54341ae181d3fc4d74a37217d1676aa9c3e7576bf63654d91deff9a5d8d9d05bR1589

This pull request is 3 years old now, and that comment a year, not entirely sure it's still relevant....

**Comment by vStone** [comment]
> 
> 
> > > i don't know why but it's adding songs twice everyta time I call play or playnext :/
> > 
> > 
> > The original add_entry is also still there. Perhaps this is the issue:
> > https://github.com/Just-Some-Bots/MusicBot/pull/1579/files#diff-54341ae181d3fc4d74a37217d1676aa9c3e7576bf63654d91deff9a5d8d9d05bR1589
> 
> This pull request is 3 years old now, and that comment a year, not entirely sure it's still relevant....

Maybe a notification is good enough to get the original author to give it some more love, or its a good opportunity to close it

**Comment by AutumnClove** [comment]
#1986 is better

**Pull request closed without merging**
