### PR TITLE
Delete LICENSE

### PR DESCRIPTION
**Pull request by NimoHax**
After creating your pull request, tick these boxes if they are applicable to you.

- [x] I have tested my changes against the `review` branch (the latest developmental version), and this pull request is targeting that branch as a base
- [x] I have tested my changes on Python 3.5/3.6

----

### CODE REVIEW

**Comment by TheerapakG** [comment]
For what reason would you want to delete the license file from the repository?

**Comment by ghost** [comment]
That file is **REQUIRED** to be there for legal reasons.

**Comment by developingrxn** [comment]
Why are you going to eliminate the license? It is something that has to do with the legal, and does not pass 1KB, that unnecessary. You do not need to eliminate it for nothing, and it's better that you leave it there, for some reason it's there.

**Comment by MattBSG** [comment]
Ya, no.

**Pull request closed without merging**
